### ISSUE TITLE
建设公司官网

### ISSUE THREAD

**Issue by sinkcup** [stonecutter/stonecutter.github.io#1]
挑一个免费模板：https://startbootstrap.com/

比如 https://github.com/BlackrockDigital/startbootstrap-stylish-portfolio

包括：公司的位置地图（腾讯或者高德，不要用百度）、公司提供的硬件设施照片

目标：掌握 GitHub Pages、Github Flow、Git 命令、英文 commit 的写法、域名的购买和DNS设置、HTTPS配置。

文档：https://sinkcup.github.io/becoming-a-geek-programmer

**Comment by sinkcup** [comment]
是做公司官网，不是项目官网。

公司：石匠科技（stonecutter.tech）
项目：不占座（buzhanzuo.com）、xxx、yyy

参考：

公司：字节跳动（bytedance.com）
项目：今日头条（toutiao.com）、抖音（douyin.com）

**Comment by sinkcup** [comment]
icon https://www.freepik.com/free-vector/a-rolling-stone_3115046.htm

**Comment by maoAmanda** [comment]
add favicon.ico
![stone](https://user-images.githubusercontent.com/40196155/51020049-49553f00-15b8-11e9-88cd-919494e76109.jpg)

**Comment by sinkcup** [comment]
看icon网站，有版权要求：免费使用需要署名。

**Comment by maoAmanda** [comment]
change favicon
![webwxgetmsgimg](https://user-images.githubusercontent.com/40196155/51095693-8ce6bd80-17f1-11e9-83a3-d3ea35c004b1.jpeg)
